# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MY_PATH: Genome Analyzer/API
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f "Genome Analyzer"/API/requirements.txt ]; then pip install -r "Genome Analyzer"/API/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Git deploy to Heroku
      # You may pin to the exact commit or the version.
      # uses: onekiloparsec/heroku-node-deploy-subfolder@85d5701f800be8126e12b7f6f47e965c71f67b56
      uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
      with:
        # Your Heroku API key. This will be used for authentication. You can find it in your Heroku account settings
        api_key: 817ea5ed-cca2-4b1c-85e9-58e17f627e6e
        # The email of your Heroku account (needed for auth).
        email: mindenslavement@gmail.com
        # The app name to use for deploying/updating
        app_name: genomicanalyzer
        # The Heroku branch name that you would like to deploy to (`master` or `main`).
        heroku_branch: master
        # The subfolder where your built code is sitted, e.g. `dist`.
        subfolder: "${MY_PATH}"
